/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.duelo_equacoes.telas;

import java.awt.Font;
import br.com.duelo_equacoes_classes.font;
import br.com.duelo_equacoes_classes.mouse;
import java.awt.Color;

/**
 *
 * @author Julimar
 */
public class TelaInicio extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicio
     */
    
    
    font f = new font();
    TelaPlacar placar = new TelaPlacar();
    TelaCadJogador  jogador = new TelaCadJogador();
    TelaRegras regras = new TelaRegras();
    
    public TelaInicio() {
        initComponents();
        //Caminho começando do pacote src
        //Path starting from the src package
        Font fontePersonalizada = f.carregarFonte(30f);
        
        btJogar.setFont(fontePersonalizada);
        btPlacar.setFont(fontePersonalizada);
        btRegras.setFont(fontePersonalizada);
        
        Color corPadrao = new Color (0, 96, 57);
        Color corDestaque = new Color (166, 137, 83);
        
        mouse.corMouse(btJogar, corPadrao, corDestaque);
        mouse.corMouse(btPlacar, corPadrao, corDestaque);
        mouse.corMouse(btRegras, corPadrao, corDestaque);
        mouse.corMouse(btSom, corPadrao, corDestaque);
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btJogar = new javax.swing.JButton();
        btRegras = new javax.swing.JButton();
        btPlacar = new javax.swing.JButton();
        btSom = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Duelo de equações - Home");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/duelo_equacoes/img/Logo.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        btJogar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/duelo_equacoes/img/Controle.png"))); // NOI18N
        btJogar.setText("JOGAR");
        btJogar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btJogar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btJogar.setIconTextGap(37);
        btJogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btJogarActionPerformed(evt);
            }
        });
        getContentPane().add(btJogar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, 297, 70));

        btRegras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/duelo_equacoes/img/Regras.png"))); // NOI18N
        btRegras.setText("REGRAS");
        btRegras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btRegras.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btRegras.setIconTextGap(45);
        btRegras.setMargin(new java.awt.Insets(2, 10, 2, 14));
        btRegras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRegrasActionPerformed(evt);
            }
        });
        getContentPane().add(btRegras, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 410, 297, -1));

        btPlacar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/duelo_equacoes/img/Placar.png"))); // NOI18N
        btPlacar.setText("PLACAR");
        btPlacar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btPlacar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btPlacar.setIconTextGap(35);
        btPlacar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPlacarActionPerformed(evt);
            }
        });
        getContentPane().add(btPlacar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 510, 297, 70));

        btSom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/duelo_equacoes/img/Som.png"))); // NOI18N
        btSom.setToolTipText("Som");
        btSom.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btSom.setPreferredSize(new java.awt.Dimension(60, 60));
        getContentPane().add(btSom, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 648, -1, 64));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/duelo_equacoes/img/Bg.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-70, -30, 560, 790));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btJogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btJogarActionPerformed
        jogador.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btJogarActionPerformed

    private void btPlacarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPlacarActionPerformed
        placar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btPlacarActionPerformed

    private void btRegrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRegrasActionPerformed
        regras.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btRegrasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btJogar;
    private javax.swing.JButton btPlacar;
    private javax.swing.JButton btRegras;
    private javax.swing.JButton btSom;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
