/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.duelo_equacoes.telas;

import br.com.duelo_equacoes_classes.font;
import br.com.duelo_equacoes_classes.mouse;
import java.awt.Color;
import java.awt.Font;

/**
 *
 * @author Julimar
 */
public class TelaPerguntas extends javax.swing.JFrame {

    /**
     * Creates new form TelaPerguntas
     */
    
    font f = new font();
    
    public TelaPerguntas() {
        initComponents();
        Font fontePersonalizada = f.carregarFonte(40f);
        
        lblPerguntas.setFont(fontePersonalizada);
        btResposta1.setFont(fontePersonalizada);
        btResposta2.setFont(fontePersonalizada);
        btResposta3.setFont(fontePersonalizada);
        
        Color corPadrao = new Color(0, 96, 57);
        Color corDestaque = new Color(166, 137, 83);

        mouse.corMouse(btResposta1, corPadrao, corDestaque);
        mouse.corMouse(btResposta2, corPadrao, corDestaque);
        mouse.corMouse(btResposta3, corPadrao, corDestaque);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDif = new javax.swing.JLabel();
        lblNivel = new javax.swing.JLabel();
        lblPtos = new javax.swing.JLabel();
        lblPontos = new javax.swing.JLabel();
        painelPerguntas = new javax.swing.JPanel();
        lblPerguntas = new javax.swing.JLabel();
        btResposta1 = new javax.swing.JButton();
        btResposta2 = new javax.swing.JButton();
        btResposta3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblDif.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblDif.setForeground(new java.awt.Color(255, 255, 255));
        lblDif.setText("Dificuldade:");
        getContentPane().add(lblDif, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 18, -1, -1));

        lblNivel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblNivel.setForeground(new java.awt.Color(255, 255, 255));
        lblNivel.setText("-");
        getContentPane().add(lblNivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 110, -1));

        lblPtos.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblPtos.setForeground(new java.awt.Color(255, 255, 255));
        lblPtos.setText("Pontos:");
        getContentPane().add(lblPtos, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, -1, -1));

        lblPontos.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblPontos.setForeground(new java.awt.Color(255, 255, 255));
        lblPontos.setText("-");
        getContentPane().add(lblPontos, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 80, -1));

        painelPerguntas.setBackground(new java.awt.Color(0, 96, 57));
        painelPerguntas.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pergunta", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N

        lblPerguntas.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        lblPerguntas.setForeground(new java.awt.Color(255, 255, 255));
        lblPerguntas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPerguntas.setText("PERGUNTA");

        javax.swing.GroupLayout painelPerguntasLayout = new javax.swing.GroupLayout(painelPerguntas);
        painelPerguntas.setLayout(painelPerguntasLayout);
        painelPerguntasLayout.setHorizontalGroup(
            painelPerguntasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPerguntasLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(lblPerguntas, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        painelPerguntasLayout.setVerticalGroup(
            painelPerguntasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPerguntasLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(lblPerguntas, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        getContentPane().add(painelPerguntas, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 460, -1));

        btResposta1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        btResposta1.setText("RESPOSTA 1");
        btResposta1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(btResposta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 392, 344, 82));

        btResposta2.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        btResposta2.setText("RESPOSTA 2");
        btResposta2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(btResposta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 492, 344, 82));

        btResposta3.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        btResposta3.setText("RESPOSTA 3");
        btResposta3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(btResposta3, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 592, 344, 82));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/duelo_equacoes/img/Bg.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 0, 500, 760));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPerguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPerguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPerguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPerguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPerguntas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btResposta1;
    private javax.swing.JButton btResposta2;
    private javax.swing.JButton btResposta3;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblDif;
    private javax.swing.JLabel lblNivel;
    private javax.swing.JLabel lblPerguntas;
    private javax.swing.JLabel lblPontos;
    private javax.swing.JLabel lblPtos;
    private javax.swing.JPanel painelPerguntas;
    // End of variables declaration//GEN-END:variables
}
